version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=habit_tracker
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - habit-tracker-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habit_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit-tracker-network

volumes:
  postgres_data:

networks:
  habit-tracker-network:
    driver: bridge 